<!-- Help page -->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Help</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel='shortcut icon' href='res/favicon.ico' type='image/x-icon'>
	<link rel="stylesheet" href="style/customerhomepage.css">
	<link href='https://fonts.googleapis.com/css?family=Patua+One'
	rel='stylesheet' type='text/css'>
</head>
<body>
	<!-- Navigation bar-->
	<div id="sidebar-container">
		<img id="logo" src="res/ss_logo.png">
		<ul class="sidebar-nav">
			<li><a href="customerhomepage.jsp">Home</a></li>
			<li><a href="#">Settings</a></li>
			<li>
				<form id='order-search' action="OrderSearchCustomer" method="post">
					<a href="javascript:{}"
						onclick="document.getElementById('order-search').submit();">My
						Orders</a>
				</form>
			</li>
			<li>
				<form id='stock-search' action="StockSearchCustomer" method="post">
					<a href="javascript:{}"
						onclick="document.getElementById('stock-search').submit();">Buy
						Stock</a>
				</form>
			</li>
			<li><a href="help.jsp">Help</a></li>
			<li><a href="Logout">Logout</a></li>
		</ul>
	</div>

	<!-- content container -->
	<div id="main-container">
		<div id="heading-container">
			<h1>Help Menu</h1>
			<hr id="title-line">
		</div>
		<br>
		
		<h2>Order Types</h2>
		<h3>Hidden Stop</h3>
		<p>
			The hidden stop order type uses a fixed hidden-stop price to automatically decide when to place a sell order.
			The order will be placed when the stock price falls to the hidden stop price.
		</p>
		<h3>Trailing Stop</h3>
		<p>
			The trailing stop order type uses a trailing stop to automatically decide when to place a sell order.
			A trailing stop is set at a percentage or dollar amount below the stock's current market price, and a sell 
			order will be placed if and when the share price falls to the trailing stop. The trailing stop is adjusted 
			as the share price fluctuates.
		</p>

		<h2>Manager Commands</h2>
		<ul>
			<li>Add, Edit and Delete information for an employee</li>
			<li>Determine which customer generated most total revenue</li>
			<li>Determine which customer representative generated most total revenue</li>
			<li>Obtain a sales report for a particular month</li>
			<li>Produce a comprehensive listing of all stocks</li>
			<li>Produce a list of orders by stock symbol or by customer name</li>
			<li>Produce a summary listing of revenue generated by a particular stock, stock type, or customer</li>
			<li>Produce a list of most actively traded stocks</li>
			<li>Set the share price of a stock (for simulating market fluctuations in a stock's share price)</li>
		</ul>
		
		<h2>Employee Commands</h2>
		<ul>
			<li>Add, Edit and Delete information for a customer</li>
			<li>Produce customer mailing lists</li>
			<li>Produce a list of stock suggestions for a given customer (based on that customer's past orders)</li>
			<li>Record an order</li>
		</ul>
		
		<h2>Customer Commands</h2>
		<ul>
			<li>A customer's current stock holdings</li>
			<li>A history of all current and past orders a customer has placed</li>
			<li>Best-Seller list of stocks</li>
			<li>The share-price and trailing-stop history for a given conditional order</li>
			<li>Personalized stock suggestion list</li>
			<li>Stocks available of a particular type and most-recent order info</li>
			<li>Stocks available with a particular keyword or set of keywords in the stock name, and most-recent order info</li>
			<li>The share-price history of a given stock over a certain period of time (e.g., past six months)</li>
			<li>The share-price and hidden-stop history for a given conditional order</li>
		</ul>
		<br><br>
		
	</div>
</body>
</html>


