//verifying this is committed
use tweet;
sh.addShard("shard1/shard1_ip:shard1_port");
sh.addShard("shard1/shard2_ip:shard2_port");
sh.addShard("shard1/shard3_ip:shard3_port");
sh.addShard("shard1/shard4_ip:shard4_port");
sh.enableSharding("tweet");
sh.shardCollection("tweet.user", {"email": 1});
sh.shardCollection("tweet.tweets", {"username": 1})
sh.shardCollection("tweet.follows", {"follower_username": 1});
sh.shardCollection("tweet.media", {"_id": 1})
sh.shardCollection("tweet.likes", {"uid": 1, "tid": 1})
sh.status();


/*

This will be generated by script...

use tweet;
sh.addShard("shard1/192.168.1.45:27040");
sh.addShard("shard2/192.168.1.46:27040");
sh.addShard("shard3/192.168.1.47:27040");
sh.addShard("shard4/192.168.1.48:27040");
sh.addShard("shard5/192.168.1.56:27040");
sh.addShard("shard6/192.168.1.57:27040");

sh.enableSharding("tweet");
sh.shardCollection("tweet.user", {"email": 1});
sh.shardCollection("tweet.tweets", {"username": 1});
sh.shardCollection("tweet.follows", {"follower_username": 1});
sh.shardCollection("tweet.media", {"_id": 1});
sh.shardCollection("tweet.likes", {"uid": 1, "tid": 1});
sh.status();
*/